services:
  api:
    build: .
    container_name: emarket-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://salahdaha7_db_user:Fr0Aw7KHAPDnsu5t@cluster0.ixl0arc.mongodb.net/?appName=Market
      - JWT_ACCESS_SECRET=1a9644d6f8822eaa8432c0a78013b2fab5a108236ee6d618a19397cb4caca97ab296f085b7bdcdbb1d2ccc7fb64292978a9e0f6f25fadcb24c1c1c4208057984
      - JWT_REFRESH_SECRET=2f6d3e147b1b7bc1ee75d001b3709b3376b76023ae2126c350fef597ab3d1df99d1111c0530547f190a9f902e3937f07597d930a546ef0bd712086037d971bd9
      - ACCESS_TOKEN_EXP=15m
      - REFRESH_TOKEN_EXP=30d
      - COOKIE_DOMAIN=localhost
      - NODE_ENV=development
      - MAILPIT_HOST=mailpit
      - MAILPIT_PORT=1025
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mailpit
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    container_name: emarket-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped