type: collection.insomnia.rest/5.0
name: Merket_API
meta:
  id: wrk_78e2805e52654133950d52826d33bdd4
  created: 1759865472927
  modified: 1759865472927
  description: ""
collection:
  - name: Product Managment
    meta:
      id: fld_84c4edac3e6b4ec09abc533aad14fb62
      created: 1759920830316
      modified: 1759920853928
      sortKey: -1759920830316
      description: ""
    children:
      - url: http://localhost:3000/api/products/create
        name: Create Products
        meta:
          id: req_8769245013804a24ac47ced1abadf5ce
          created: 1759865490837
          modified: 1760037864865
          isPrivate: false
          description: ""
          sortKey: -1759920836806
        method: POST
        body:
          mimeType: application/json
          text: |
            {
              "title": "Casque Casuqe",
              "description": "Casque antibruit  de 30h.",
              "prix": 3599,
              "stock": 12,
              "imageUrl": "https://example.com/sony-xm5.jpg",
            	"categories" : [
            		"68e8080a186e0c45a07b0574",
            		"68e8080d186e0c45a07b0576"
            	]
            }
        headers:
          - name: Content-Type
            value: application/json
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/products/
        name: Get Products
        meta:
          id: req_16f6d7455e734fda8a707ead1361d755
          created: 1759871016263
          modified: 1759920845834
          isPrivate: false
          description: ""
          sortKey: -1759920836706
        method: GET
        headers:
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/products/delete/68e585d6415ce575c1099da7
        name: Delete Product
        meta:
          id: req_c89bcb3d95a145d6abb019b241410e48
          created: 1759872250820
          modified: 1760006033388
          isPrivate: false
          description: ""
          sortKey: -1759920836606
        method: DELETE
        headers:
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/products/update/68e585d6415ce575c1099da7
        name: Update Product
        meta:
          id: req_30fc3d52bdcc47e181a98b99a8a365f1
          created: 1759914223115
          modified: 1759920836541
          isPrivate: false
          description: ""
          sortKey: -1759920836506
        method: PUT
        body:
          mimeType: application/json
          text: >
            {
              "title": "Casque Bluetooth",
              "description": "Casque antibruit haut de gamme avec autonomie de 30h.",
              "prix": 3599,
              "stock": 12,
              "categorie": "Électronique",
              "imageUrl": "https://example.com/sony-xm5.jpg"
            }
        headers:
          - name: Content-Type
            value: application/json
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/products/search?=name=casque
        name: Search Products
        meta:
          id: req_e015f7582ed14ebbbc795769e89eebee
          created: 1760091216566
          modified: 1760091259762
          isPrivate: false
          description: ""
          sortKey: -1760091216566
        method: GET
        headers:
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
  - name: User Management
    meta:
      id: fld_ba5767db2ff74b8e8e1c6af205846151
      created: 1759920873517
      modified: 1759920873517
      sortKey: -1759920873517
      description: ""
    children:
      - url: http://localhost:3000/api/users
        name: Get Usrers
        meta:
          id: req_85be79e065354867b736c899f375dc04
          created: 1759920909312
          modified: 1760002293091
          isPrivate: false
          description: ""
          sortKey: -1759920909312
        method: GET
        body:
          mimeType: application/json
          text: ""
        headers:
          - name: Content-Type
            value: application/json
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/users/create
        name: Create User
        meta:
          id: req_e8902d1368354edca7c79769ea55e65f
          created: 1760001245778
          modified: 1760031924002
          isPrivate: false
          description: ""
          sortKey: -1760001245778
        method: POST
        body:
          mimeType: application/json
          text: |-
            {
            	"fullName" : "khalid",
            	"email" : "khalid@gmail.com",
            	"password" : "12341234"
            }
        headers:
          - name: Content-Type
            value: application/json
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/users/delete/68e7893fe63c1bd20064e455
        name: Delete User
        meta:
          id: req_b35e144e470a4510823e9daa6df2fc0b
          created: 1760003651881
          modified: 1760004993381
          isPrivate: false
          description: ""
          sortKey: -1760003651881
        method: DELETE
        headers:
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/users/update/68e7893fe63c1bd20064e455
        name: Update User
        meta:
          id: req_02dda9adfcd04ab5915e4e7d5ac92c6f
          created: 1760006224234
          modified: 1760006469792
          isPrivate: false
          description: ""
          sortKey: -1760006224234
        method: PUT
        body:
          mimeType: application/json
          text: |-
            {
            	"fullName" : "ayoub",
            	"email" : "ayoub@gmail.com",
            	"password" : "salah1234"
            }
        headers:
          - name: Content-Type
            value: application/json
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
  - name: Category Management
    meta:
      id: fld_5fa1b3164d254c3ab60715149cbf51fc
      created: 1760035270090
      modified: 1760035270090
      sortKey: -1760035270090
      description: ""
    children:
      - url: "http://localhost:3000/api/categorie/ "
        name: Get Categories
        meta:
          id: req_48c81ec162c044ceac80aed512a1f18c
          created: 1760035274925
          modified: 1760035306947
          isPrivate: false
          description: ""
          sortKey: -1760035274925
        method: GET
        headers:
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/categorie/create
        name: Create Categorie
        meta:
          id: req_621cd888ce1e4ba3b26a68b39cd85288
          created: 1760035310249
          modified: 1760036876400
          isPrivate: false
          description: ""
          sortKey: -1760035310249
        method: POST
        body:
          mimeType: application/json
          text: |-
            {
            	"name" : "Electronique 2",
            	"description" : "lorem eckrnv ckwejnc cjwibec cwbeicbwe ciwubhc"
            }
        headers:
          - name: Content-Type
            value: application/json
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/categorie/update/68e8024d71c80b3f36c6b487
        name: Update Categorie
        meta:
          id: req_d5924757f98a45c2929d5f1bbce0c6f7
          created: 1760035417387
          modified: 1760035511104
          isPrivate: false
          description: ""
          sortKey: -1760035417387
        method: PUT
        body:
          mimeType: application/json
          text: |-
            {
            	"name" : "Neuvoux Category",
            	"description" : "updated categorie"
            }
        headers:
          - name: Content-Type
            value: application/json
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: http://localhost:3000/api/categorie/delete/68e8024d71c80b3f36c6b487
        name: Delete Categorie
        meta:
          id: req_99e79c4810ce4dc0a6ee701e88d8299a
          created: 1760035660648
          modified: 1760035739421
          isPrivate: false
          description: ""
          sortKey: -1760035660648
        method: DELETE
        headers:
          - name: User-Agent
            value: insomnia/11.6.1
        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
cookieJar:
  name: Default Jar
  meta:
    id: jar_6959f343a49fa757cd368b7ad2cf96304d8f676c
    created: 1759865472932
    modified: 1759865472932
environments:
  name: Base Environment
  meta:
    id: env_6959f343a49fa757cd368b7ad2cf96304d8f676c
    created: 1759865472930
    modified: 1759865472930
    isPrivate: false
